### ISSUE TITLE
跑起来看不到项目内容

### ISSUE THREAD

**Issue by winner004** [webyang-male/nuxt3-edu#2]
按照文档运行起来了但看不到项目内容，运行起来是nuxt页面提示要创建一个app.vue
<img width="807" alt="image" src="https://user-images.githubusercontent.com/24785109/181471029-996bb6db-55bf-4c77-91d2-5a619e128a95.png">

**Comment by webyang-male** [comment]
> 按照文档运行起来了但看不到项目内容，运行起来是nuxt页面提示要创建一个app.vue <img alt="image" width="807" src="https://user-images.githubusercontent.com/24785109/181471029-996bb6db-55bf-4c77-91d2-5a619e128a95.png">
抱歉才看到你的问题，我下载重新运行没问题。
1.首先你要确认你的环境依赖是否和我的一样，建议先比对一下`package.json`
2.是否命令输入错误，安装建议使用`yarn install`，安装完成后启动命令为`yarn dev -o`（-o可以自动打开浏览器查看效果）
