### ISSUE TITLE
Cannot start nuxt:  nuxt.options.serverMiddleware is not iterable

### ISSUE THREAD

**Issue by OnePsycho** [webyang-male/nuxt3-edu#4]
运行项目 install 之后 npm run dev 运行不起来  如图所示
![image](https://user-images.githubusercontent.com/43296632/205567623-b9a3cd09-e03a-49f7-b09d-4bef3fd28595.png)

**Comment by webyang-male** [comment]
> 运行项目 install 之后 npm run dev 运行不起来  如图所示
> ![image](https://user-images.githubusercontent.com/43296632/205567623-b9a3cd09-e03a-49f7-b09d-4bef3fd28595.png)
> 

似乎是端口被占了，看看npm run dev -o是什么反应

**Comment by JUST-Limbo** [comment]
使用`pnpm i`安装依赖，执行`pnpm run dev`能复现此问题，改用`yarn`安装后问题消失。
在此告知后续看到此处的开发者。
