### ISSUE TITLE
show data in view page source

### ISSUE THREAD

**Issue by alirezaaghaeee** [webyang-male/nuxt3-edu#5]
its not directly related to this project but i want ask about show my nuxt 3 app content in page source but its does not shown there ,what config or process need to achieve this goal?

**Comment by webyang-male** [comment]
> its not directly related to this project but i want ask about show my nuxt 3 app content in page source but its does not shown there ,what config or process need to achieve this goal?


You should modify the api interface of the file marked in the figure to get the data, the interface address is
http://ceshi13.dishait.cn
![IMG_20230208_222924.jpg](https://user-images.githubusercontent.com/52821367/217558734-b2687167-c2b7-49d3-baaa-bdab2f6306d9.jpg)

**Comment by alirezaaghaeee** [comment]
> > its not directly related to this project but i want ask about show my nuxt 3 app content in page source but its does not shown there ,what config or process need to achieve this goal?
> 
> 
> You should modify the api interface of the file marked in the figure to get the data, the interface address is
> http://ceshi13.dishait.cn
> ![IMG_20230208_222924.jpg](https://user-images.githubusercontent.com/52821367/217558734-b2687167-c2b7-49d3-baaa-bdab2f6306d9.jpg)
> 
> 

i didn't understand very well,let me give more info about my project.I use axios for sending request ,can axios do this for me ?
my main goal is show page content in view page source when page load ,but now all the Things shown in view page source is a html file with some style link in it without any data of my project,before this I thought in behind nuxt should did it

**Comment by alirezaaghaeee** [comment]
> > its not directly related to this project but i want ask about show my nuxt 3 app content in page source but its does not shown there ,what config or process need to achieve this goal?
> 
> You should modify the api interface of the file marked in the figure to get the data, the interface address is http://ceshi13.dishait.cn ![IMG_20230208_222924.jpg](https://user-images.githubusercontent.com/52821367/217558734-b2687167-c2b7-49d3-baaa-bdab2f6306d9.jpg)

![image](https://user-images.githubusercontent.com/68455964/217714038-bfc117bf-c27a-4659-9c26-9a7b4990d268.png)
  
all the thing i see
